# Generated by Django 4.1 on 2023-01-21 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handle_image', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogError',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField(null=True)),
                ('description', models.CharField(default='', max_length=500)),
            ],
        ),
    ]
